version: "3.7"

services: 
  nginx:
    build:
      context: "nginx"
    hostname: "nginx"
    container_name: "nginx"
    working_dir: "/var/www/html/"
    restart: always
    ports:
      - "8005:8005"
    volumes:
      - "${WEBROOT}:/var/www/html/"
    environment:
      PS1: "\\u@\\h:\\w\\$$ "
