version: '3.7'
services:
  node:
    working_dir: "/var/www/html"
    build:
      context:  "node"    
    container_name: "node"       
    ports:
      - "80:3000"
      - "300:3001"
    volumes:
      - "${WEBROOT}:/var/www/html/"
  redis :
    container_name: "redis"
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    networks:
      node_networks:
        aliases:
          - redis_host
networks:
  node_networks:
    name: node_net
    driver: bridge
    ipam:
      driver: default
